#if UNITY_EDITOR
using System;
using System.IO;
using System.Reflection;
using System.Text.RegularExpressions;
using JetBrains.Annotations;
using Systems.SimpleCore.Automation.Attributes;
using Systems.SimpleCore.Editor.Utility;
using UnityEditor;
using UnityEngine;

namespace Systems.SimpleCore.Editor.Automation
{
    /// <summary>
    ///     Script used to automatically create ScriptableObjects
    /// </summary>
    [InitializeOnLoad] public static class AutoGeneratedScriptableObjectCreator
    {
        /// <summary>
        ///     Processes all objects in the project
        /// </summary>
        private static void ProcessAllObjects()
        {
            bool anyObjectChanged = false;

            AssetDatabase.StartAssetEditing();
            try
            {
                // Loop through all assemblies in project
                for (int i = 0; i < AppDomain.CurrentDomain.GetAssemblies().Length; i++)
                {
                    Assembly assembly = AppDomain.CurrentDomain.GetAssemblies()[i];
                    string assemblyName = assembly.GetName().Name;
                    if (assemblyName.EndsWith(".Tests", StringComparison.Ordinal)) continue;

                    // Loop through all types in assembly
                    Type[] types = assembly.GetTypes();
                    for (int index = 0; index < types.Length; index++)
                    {
                        Type type = types[index];
                        // Check if type is a ScriptableObject, if not, skip
                        if (!typeof(ScriptableObject).IsAssignableFrom(type)) continue;
                        if (!BuildObject(type)) continue;
                        anyObjectChanged = true;
                    }
                }
            }
            finally
            {
                AssetDatabase.StopAssetEditing();
            }

            // Save and refresh if any object was changed
            if (!anyObjectChanged) return;
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        private static bool BuildObject([NotNull] Type type)
        {
            // Check if not abstract nor interface
            if (type.IsAbstract || type.IsInterface) return false;

            // Check if object has AutoCreatedObject attribute
            AutoCreateAttribute attribute = type.GetCustomAttribute<AutoCreateAttribute>(true);
            if (ReferenceEquals(attribute, null)) return false;

            string typeName = type.Name;

            // Remove invalid characters from type name
            Regex rgx = new("[^a-zA-Z0-9 -]");
            typeName = rgx.Replace(typeName, "");

            string directory = "Assets/Generated/" + attribute.Path;
            string path = directory + "/" + typeName + ".asset";
 

            // Ensure directory exists
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            // Try load existing asset
            UnityEngine.Object existing =
                AssetDatabase.LoadAssetAtPath(path, typeof(ScriptableObject));
            ScriptableObject instance = null;

            if (!ReferenceEquals(existing, null))
            {
                // Check if type matches
                if (existing.GetType() == type)
                {
                    instance = (ScriptableObject) existing;
                }
                else
                {
                    Debug.LogError(
                        $"Found existing asset of type {existing.GetType().FullName} at {path} which is not " +
                        $"valid for type {type.FullName}");
                    return false;
                }
            }

            // Create new instance if not found
            if (ReferenceEquals(instance, null))
            {
                if (!CanCreateStableAsset(type, path)) return false;

                if (File.Exists(path))
                {
                    Debug.LogWarning($"Replacing broken generated ScriptableObject asset at {path}");
                    AssetDatabase.DeleteAsset(path);
                }

                instance = ScriptableObject.CreateInstance(type);

                // Create asset
                AssetDatabase.CreateAsset(instance, path);

                Debug.Log($"Created ScriptableObject of type {type.FullName} at {path}");
            }

            // Check if instance is null  
            if (ReferenceEquals(instance, null))
            {
                Debug.LogError($"Failed to create ScriptableObject of type {type.FullName}");
                return false; 
            }  

            // Mark asset as addressable
            AddressableExtensions.MarkAssetAddressable(path, attribute.Path, label: attribute.Label);

            return true;
        }

        private static bool CanCreateStableAsset([NotNull] Type type, [NotNull] string path)
        {
            MonoScript script = FindScriptForType(type);
            if (script) return true;

            Debug.LogError(
                $"Cannot create generated ScriptableObject asset at {path} for {type.FullName}. " +
                "Unity cannot resolve a MonoScript for this type. Move the concrete ScriptableObject " +
                "class into its own matching .cs file so Unity can serialize the generated asset safely.");
            return false;
        }

        [CanBeNull]
        private static MonoScript FindScriptForType([NotNull] Type type)
        {
            string[] scriptGuids = AssetDatabase.FindAssets(type.Name + " t:MonoScript");
            for (int scriptIndex = 0; scriptIndex < scriptGuids.Length; scriptIndex++)
            {
                string scriptPath = AssetDatabase.GUIDToAssetPath(scriptGuids[scriptIndex]);
                MonoScript script = AssetDatabase.LoadAssetAtPath<MonoScript>(scriptPath);
                if (!script) continue;
                if (script.GetClass() != type) continue;
                return script;
            }

            return null;
        }

        static AutoGeneratedScriptableObjectCreator()
        {
            // Auto-generate all objects on domain reload
            ProcessAllObjects();
        }
    }
}
#endif
