#if UNITY_EDITOR
using System.Reflection;
using Systems.SimpleCore.Automation.Attributes;
using UnityEditor;
using UnityEngine;

namespace Systems.SimpleCore.Editor.Automation
{
    /// <summary>
    ///     Postprocessor preventing move of Assets/Generated scripts
    /// </summary>
    public sealed class PreventMovingAutoGeneratedFilesAssetPostprocessor : AssetModificationProcessor
    {
        private static AssetMoveResult OnWillMoveAsset(string sourcePath, string destinationPath)
        {
            if (!IsAutoGeneratedAsset(sourcePath)) return AssetMoveResult.DidNotMove;

            // Asset is auto generated, prevent moving
            Debug.LogError($"Cannot move auto generated file at {sourcePath} to {destinationPath}");
            return AssetMoveResult.FailedMove;
        }
        
        private static AssetDeleteResult OnWillDeleteAsset(string assetPath, RemoveAssetOptions options)
        {
            if(!IsAutoGeneratedAsset(assetPath)) return AssetDeleteResult.DidNotDelete;
            
            // Asset is auto generated, prevent moving
            Debug.LogError($"Cannot delete auto generated file at {assetPath}");
            return AssetDeleteResult.FailedDelete;
        }

        private static bool IsAutoGeneratedAsset(string assetPath)
        {
            // Get asset at desired path
            Object asset = AssetDatabase.LoadAssetAtPath<Object>(assetPath);
            if (!asset) return false;

            // Check if asset is auto generated (get by attribute)
            if (asset is not ScriptableObject scriptableObject) return false;
            
            // Check if asset is auto generated scriptable object
            return scriptableObject.GetType().GetCustomAttribute<AutoCreateAttribute>(true) != null;
        }
    }
}
#endif